INSERT INTO TB_INSTITUTION (id, name)
SELECT Long(), 'UMEF Alto Monforte'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_INSTITUTION WHERE name = 'UMEF Alto Monforte');

INSERT INTO TB_INSTITUTION (id, name)
SELECT Long(), 'UMEF Antônio Padoani'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_INSTITUTION WHERE name = 'UMEF Antônio Padoani');

INSERT INTO TB_INSTITUTION (id, name)
SELECT Long(), 'UMEF José Feriani'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_INSTITUTION WHERE name = 'UMEF José Feriani');

INSERT INTO TB_INSTITUTION (id, name)
SELECT Long(), 'UMEF Mata Fria'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_INSTITUTION WHERE name = 'UMEF Mata Fria');

INSERT INTO TB_INSTITUTION (id, name)
SELECT Long(), 'UMEF Prof. Édson Altô'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_INSTITUTION WHERE name = 'UMEF Prof. Édson Altô');

INSERT INTO TB_INSTITUTION (id, name)
SELECT Long(), 'UMEF Professor Antônio Azeredo Coutinho'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_INSTITUTION WHERE name = 'UMEF Professor Antônio Azeredo Coutinho');

INSERT INTO TB_INSTITUTION (id, name)
SELECT Long(), 'UMEF Santa Luzia'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_INSTITUTION WHERE name = 'UMEF Santa Luzia');

INSERT INTO TB_INSTITUTION (id, name)
SELECT Long(), 'UMEI Brís Lacerda Amigo'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_INSTITUTION WHERE name = 'UMEI Brís Lacerda Amigo');

INSERT INTO TB_INSTITUTION (id, name)
SELECT Long(), 'UMEI H. L. Lorentzen'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_INSTITUTION WHERE name = 'UMEI H. L. Lorentzen');

INSERT INTO TB_INSTITUTION (id, name)
SELECT Long(), 'UMEI Vovó Clara'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_INSTITUTION WHERE name = 'UMEI Vovó Clara');

INSERT INTO TB_INSTITUTION (id, name)
SELECT Long(), 'UMEI Vovó Natalina Padoani'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_INSTITUTION WHERE name = 'UMEI Vovó Natalina Padoani');

INSERT INTO TB_INSTITUTION (id, name)
SELECT Long(), 'Secretaria de Educação'
FROM dual
WHERE NOT EXISTS (SELECT 1 FROM TB_INSTITUTION WHERE name = 'Secretaria de Educação');
